---
environment_version: e0955a92a761d5845520a82dcca596af
cidr_networks:
  container: 172.29.236.0/24
  tunnel: 172.29.240.0/24
  storage: 172.29.244.0/24

used_ips:
  - 172.29.236.1,172.29.236.20
  - 172.29.240.1,172.29.240.20
  - 172.29.244.1,172.29.244.20

global_overrides:
  internal_lb_vip_address: 172.29.236.7
  external_lb_vip_address: 172.29.236.7
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        ip_from_q: "container"
    - network:
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
        type: "raw"
        container_bridge: "br-storage"
        container_interface: "eth2"
        ip_from_q: "storage"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vxlan"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_interface: "eth11"
        type: "flat"
        net_name: "vlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
  # Name of load balancer
  lb_name: 172.29.236.7

infra_hosts:
  infra1:
    ip: 172.29.236.2

compute_hosts:
  compute1:
    ip: 172.29.236.10
  compute2:
    ip: 172.29.236.11
  compute3:
    ip: 172.29.236.12

storage_hosts:
  cinder1:
    ip: 172.29.236.6
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMISCSIDriver
          volume_backend_name: LVM_iSCSI
  cinder2:
    ip: 172.29.236.9
    container_vars:
      #cinder_storage_availability_zone: cinderAZ_2
      #cinder_default_availability_zone: cinderAZ_2
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMISCSIDriver
          volume_backend_name: LVM_iSCSI_2

log_hosts:
  logger1:
    ip: 172.29.236.5

network_hosts:
  infra1:
    ip: 172.29.236.2

haproxy_hosts:
  deploy1:
    ip: 172.29.236.7